### ISSUE TITLE
[Feature request] Allow `<Label>` in River + Bentos

### ISSUE THREAD

**Issue by simurai** [primer/brand#508]
## Problem

The [Copilot page has features](https://github.com/features/copilot#features) that are not available for everyone. So we used a `<Label>` to mark something as only available for "Enterprise".

River | Bento
--- | ---
![Image](https://github.com/primer/brand/assets/378023/21cee598-49c6-4a80-ae13-edc51fc21af6) | ![Image](https://github.com/primer/brand/assets/378023/e74b0735-16fb-43dd-8c8c-892fd25507b4)

Unfortunately, `<Label>` is not supported as a child of `River` and `Bento`.

## Possible solution

Allow `<Label>` as a child of `River` and `Bento`. Ideally, positioned at the top.

## Urgency

This is not too urgent. The [current workaround](https://github.com/github/github/blob/a521c105b6c01a27c9efcdead1438489a33cb0ac/ui/packages/landing-pages/routes/CopilotIndex.tsx#L717-L720) is not very pretty, but works for now:

1. Add the `<Label>` **inside** `<Heading>`. 😈
2. Then use some custom styles to reset the inherited `<Heading>` styles.

```jsx
<River.Content>
  <Heading as="h3">
    <Label className="Label--inRiver">Copilot Enterprise</Label>
    Docs that feel tailored for you.
  </Heading>
```

```css
.Label--inRiver {
  display: block;
  width: fit-content;
  margin-bottom: var(--brand-River-heading-margin);
  font-size: var(--brand-text-size-300);
  letter-spacing: normal;
}
```
