### ISSUE TITLE
[a11y] `SubNav` links unaccessible on 200% zoom

### ISSUE THREAD

**Issue by stamat** [primer/brand#845]
Links are not accessible at all when the page is zoomed to 200% and the height of the window is small. Try it out on 320x256 screen size.

Issue is present on the current `/features` page where `SubNav` is used instead of the `AnchorNav` since the latter can support only few links (also a thing to look at).

A11y audit marked this issue as **Sev 2**

- Issue: https://github.com/github/accessibility-audits/issues/9847

I've placed an override in this PR: https://github.com/github/github/pull/353042

```css
.lp-SubNav {
  padding: 0;
  overflow-y: auto;
  max-height: 100vh;
  min-height: 56px;

  ul {
    padding: var(--base-size-16);
    background-color: var(--brand-color-canvas-default);

    @media screen and (min-width: 1012px) {
      padding: var(--base-size-20) var(--base-size-32);
      background: none;
    }
  }
}
```

I know that we are making a `SubNav v2` but we need to make sure that this issue doesn't persist.
